package getTaskexecutions.repository.types;

public enum ProcessStepDetailStateType {

	BEST_BURGER_INITIAL_STATE,
	BEST_BURGER_EQUIPMENT_STATE,
	BEST_BURGER_PATTY_TYPE_STATE,
	BEST_BURGER_GRILL_TIME_STATE,
	BEST_BURGER_RUN_SIZE_STATE,
	BEST_BURGER_MEASUREMENT_STATE,
	BEST_BURGER_QUESTION_STATE,
	BEST_BURGER_POSTPONED_STATE,
	BEST_BURGER_CONTINUED_STATE,
	BEST_BURGER_RESULT_STATE,
	BEST_BURGER_CORRECTIVE_ACTION_STATE
}
